package CRDT;
import java.util.SortedMap;
import java.util.TreeMap;
public class BlockNode {
    // Variables mapped directly from your UML
    private PositionID blockId;
    private boolean isDeleted;
    private TreeMap<PositionID, CharNode> characters;

    /**
     * Constructor for a new block.
     */
    public BlockNode(PositionID blockId) {
        this.blockId = blockId;
        this.isDeleted = false; // Blocks start out active, del=0[cite: 470, 479].
        this.characters = new TreeMap<>(); // This automatically sorts characters!
    }

    /**
     * Inserts a new character into the block.
     */
    public void insertChar(PositionID charId, char value) {
        CharNode newNode = new CharNode(charId, value);
        characters.put(charId, newNode);
    }

    /**
     * Deletes a character by applying a tombstone.
     */
    public void deleteChar(PositionID charId) {
        CharNode node = characters.get(charId);
        if (node != null) {
            node.markDeleted(); // Characters are NOT physically removed[cite: 490].
        }
    }

    /**
     * Splits this block into two separate logical units[cite: 518].
     * * @param splitCharId The position ID where the split should happen.
     * @param newBlockId The ID for the newly created block (generated by the Document).
     * @return The newly created BlockNode containing the second half of the text.
     */
    public BlockNode splitAt(PositionID splitCharId, PositionID newBlockId) {
        // 1. Create the new block
        BlockNode newBlock = new BlockNode(newBlockId);

        // 2. TreeMap makes splitting incredibly easy using tailMap!
        // tailMap gets all characters starting from the splitCharId to the end.
        SortedMap<PositionID, CharNode> tail = characters.tailMap(splitCharId);

        // 3. Copy those characters into the new block
        newBlock.characters.putAll(tail);

        // 4. Remove them from this current block
        tail.clear();

        return newBlock;
    }

    /**
     * Helper method to mark the entire block as deleted.
     */
    public void markDeleted() {
        this.isDeleted = true;
    }

    // --- Getters ---
    public PositionID getBlockId() { return blockId; }
    public boolean isDeleted() { return isDeleted; }
    public TreeMap<PositionID, CharNode> getCharacters() { return characters; }

    /**
     * Helper method to print the block's current text for local testing.
     */
    @Override
    public String toString() {
        if (isDeleted) return "";

        StringBuilder sb = new StringBuilder();
        // Since it's a TreeMap, iterating through the values is automatically in the correct order!
        for (CharNode node : characters.values()) {
            sb.append(node.toString()); // This implicitly skips deleted characters
        }
        return sb.toString();
    }
}
